#+date: \today

#+latex_class: qptiet
#+latex_class_options: [11pt]
#+options: num:nil toc:nil author:nil email:nil 

#+latex_header_extra: \hypersetup{%
#+latex_header_extra:   colorlinks,%
#+latex_header_extra:   breaklinks,%
#+latex_header_extra:   urlcolor=[rgb]{0,0.35,0.65},%
#+latex_header_extra:   linkcolor=[rgb]{0,0.35,0.65}%
#+latex_header_extra: }

#+latex_header_extra: \usepackage{libertinus}

#+latex_header_extra: \schoolordepartment{%
#+latex_header_extra: Computer Science \& Engineering Department}
#+latex_header_extra: \examname{End Semester Examination}
#+latex_header_extra: \coursecode{UCS505}
#+latex_header_extra: \coursename{Computer Graphics}
#+latex_header_extra: \timeduration{3 hours}
#+latex_header_extra: \maxmarks{45}
#+latex_header_extra: \faculty{ANG,AMK,HPS,YDS,RGB}

#+latex: \maketitle

*Instructions:*
1. Attempt any 5 questions;
2. Attempt all the subparts of a question at one place.

#+latex: \bvrhrule\bvrskipline

1. 
   1. Given the control polygon $\textbf{b}_0,
      \textbf{b}_1, \textbf{b}_2, \textbf{b}_3$ of a
      Cubic Bezier curve; determine the vertex
      coordinates for parameter values $\forall t\in
      T$. \hfill [7 marks]
      \begin{align*}
        T \equiv
        & \{0, 0.15, 0.35, 0.5, 0.65, 0.85, 1\} \\
        \begin{bmatrix}
          \textbf{b}_0 &\textbf{b}_1& \textbf{b}_2& \textbf{b}_3
        \end{bmatrix} \equiv& \begin{bmatrix}
          1&2&4&3\\ 1&3&3&1
        \end{bmatrix}
      \end{align*}

   2. Explain the role of convex hull in curves.
      \hfill[2 marks]

#+latex: \bvrhrule

#+ATTR_LATEX: :options [resume]
1. 
   1. Describe the continuity conditions for
      curvilinear geometry.  \hfill[5 marks]
   2. Define formally, a B-Spline curve. \hfill [2
      marks]
   3. How is a Bezier curve different from a B-Spline
      curve? \hfill [2 marks]

#+latex: \bvrhrule

#+ATTR_LATEX: :options [resume]
1. 
   1. Given a triangle, with vertices defined by column
      vectors of $P$; find its vertices after
      reflection across XZ plane. \hfill [3 marks]
      \begin{align*}
        P\equiv
        &\begin{bmatrix}
          3&6&5 \\ 4&4&6 \\ 1&2&3
        \end{bmatrix}
      \end{align*}
   2. Given a pyramid with vertices defined by the
      column vectors of $P$, and an axis of rotation
      $A$ with direction $\textbf{v}$ and passing
      through $\textbf{p}$.  Find the coordinates of
      the vertices after rotation about $A$ by an angle
      of $\theta=\pi/4$.\hfill [6 marks]
      \begin{align*}
        P\equiv
        &\begin{bmatrix}
          0&1&0&0 \\ 0&0&1&0 \\0&0&0&1
        \end{bmatrix} \\
        \begin{bmatrix}
          \mathbf{v} & \mathbf{p}
        \end{bmatrix}\equiv
        &\begin{bmatrix}
          0&0 \\1&1\\1&0
        \end{bmatrix}
      \end{align*}
#+latex: \bvrhrule

#+ATTR_LATEX: :options [resume]
1. 
   1. Explain the two winding number rules for inside
      outside tests. \hfill [4 marks]
   2. Explain the working principle of a CRT. \hfill [5
      marks]

#+latex: \bvrhrule

#+ATTR_LATEX: :options [resume]
1. 
   1. Given a projection plane $P$ defined by normal
      $\textbf{n}$ and a reference point $\textbf{a}$;
      and the centre of projection as $\mathbf{p}_0$;
      find the perspective projection of the point
      $\textbf{x}$ on $P$. \hfill [5 marks]
      \begin{align*}
        \begin{bmatrix}
          \mathbf{a}&\mathbf{n}&\mathbf{p}_0&\mathbf{x}
        \end{bmatrix}\equiv
        &
          \begin{bmatrix}
            3&-1&1&8\\4&2&1&10\\5&-1&3&6
          \end{bmatrix}
      \end{align*}
   2. Given a geometry $G$, which is a standard unit
      cube scaled uniformly by half and viewed through
      a Cavelier projection bearing $\theta=\pi/4$
      wrt. $X$-axis. \hfill [2 marks]
   3. Given a view coordinate system (VCS) with origin
      at $\textbf{p}_v$ and euler angles ZYX as
      $\boldsymbol{\theta}$ wrt. the world coordinate
      system (WCS); find the location $\mathbf{x}_v$ in
      VCS, corresponding to $\textbf{x}_w$ in
      WCS. \hfill [2 marks]
      \begin{align*}
        \begin{bmatrix}
          \mathbf{p}_v & \boldsymbol{\theta} & \mathbf{x}_w
        \end{bmatrix}\equiv
        &\begin{bmatrix}
          5&\pi/3&10\\5&0&10\\0&0&0
        \end{bmatrix}
      \end{align*}

#+latex: \bvrhrule

#+ATTR_LATEX: :options [resume]
1. 
   1. Describe the visible surface detection problem in
      about 25 words. \hfill [1 mark]
   2. To render a scene with $N$ polygons into a
      display with height $H$; what are the space and
      time complexities respectively of a typical
      image-space method. \hfill [2 marks]
   3. Given a 3D space bounded within $[0\quad0\quad0]$
      and $[7\quad7\quad-7]$, containing two infinite
      planes each defined by 3 incident points
      $\mathbf{a}_0, \mathbf{a}_1, \mathbf{a}_2$ and
      $\mathbf{b}_0, \mathbf{b}_1, \mathbf{b}_2$
      respectively bearing colours (RGB) as
      $\mathbf{c}_a$ and $\textbf{c}_b$ respectively.
      \begin{align*}
        \begin{bmatrix}
          \mathbf{a}_0&\mathbf{a}_1&\mathbf{a}_2
          &\mathbf{b}_0&\mathbf{b}_1&\mathbf{b}_2
          &\mathbf{c}_a&\mathbf{c}_b
        \end{bmatrix}\equiv
        &\begin{bmatrix}
          1&6&1&6&1&6&1&0 \\
          1&3&6&6&3&1&0&0 \\
          -1&-6&-1&-1&-6&-1&0&1
        \end{bmatrix}
      \end{align*}
      Compute and/ or determine using the depth-buffer
      method, the colour at pixel $\mathbf{x}=(2,4)$ on
      a display resolved into $7\times7$ pixels. The
      projection plane is at $Z=0$, looking at
      $-Z$. \hfill [6 marks]

#+latex: \bvrhrule


# Local Variables:
# org-latex-default-packages-alist: nil
# org-latex-packages-alist: nil
# End:
